# fly.toml app configuration file generated for nest-fly-deploy on 2023-06-23T13:53:46+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nest-fly-deploy"
primary_region = "ams"

[env]
  BASE_URL = "http://localhost:3000"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
